### ISSUE TITLE
convert to ggplotly?

### ISSUE THREAD

**Issue by connorrothschild** [connorrothschild/covid-mobility#1]
On the shiny [dashboard](https://github.com/connorrothschild/covid-mobility/blob/master/viz/app.R), making the ggplots into plotly objects would allow the user to hover and see county info in scatterplots

https://www.rdocumentation.org/packages/plotly/versions/4.9.2.1/topics/ggplotly

**Comment by kyranstar** [comment]
https://stackoverflow.com/questions/47754080/add-vertical-line-to-ggplotly-plot
