### ISSUE TITLE
Collapse two 'cases vs mobility' charts into one

### ISSUE THREAD

**Issue by connorrothschild** [connorrothschild/covid-mobility#3]
Right now, the below plot duplicates the above with minimal new info

<img width="945" alt="image" src="https://user-images.githubusercontent.com/13339581/79611633-a9426b80-80c0-11ea-95cc-390add2ee6a2.png">

Could we create one plot that looks like the top one but a button allows the user to toggle on/off policies?

**Comment by kyranstar** [comment]
Fixed, I'm gonna consolidate this into the second page as well
